Bookmarks.Web/Controllers/BookmarksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookmarks.Models;
using Bookmarks.Data;
using Bookmarks.Web.ViewModels;
using Bookmarks.Web.Filters;
using WebMatrix.WebData;

namespace Bookmarks.Web.Controllers
{
    public class BookmarksController : Controller
    {
        private BookmarksContext db = new BookmarksContext();

        //
        // GET: /Bookmarks/

        [HttpGet, Authorize, InitializeSimpleMembership]
        public ActionResult Index(string categoryName, string title, string url)
        {
            var user = GetUser();
            var userCategories = db.Categories
                .Where(x => x.User.UserId == user.UserId && !x.IsDeleted)
                .Select(x => x.Name)
                .ToList();

            ViewData["Category"] = new SelectList(userCategories);

            var bookmarks = db.Bookmarks
                .Where(x => x.User.UserId == user.UserId && !x.IsDeleted);

            if (!string.IsNullOrEmpty(categoryName))
            {
                bookmarks = bookmarks.Where(x => x.Category.Name.Contains(categoryName));
            }
            if (!string.IsNullOrEmpty(title))
            {
                bookmarks = bookmarks.Where(x => x.Title.Contains(title));
            }
            if (!string.IsNullOrEmpty(url))
            {
                bookmarks = bookmarks.Where(x => x.Url.Contains(url));
            }

            var model = bookmarks
                .Select(x => new DisplayBookmarkViewModel()
                 {
                     Id = x.Id,
                     Url = x.Url,
                     Title = x.Title,
                     Description = x.Description,
                     Category = x.Category.Name,
                     LastEdit = x.LastEdit,
                 });

            return View(model);
        }

        //
        // GET: /Bookmarks/Details/5

        public ActionResult Details(int id = 0)
        {
            Bookmark bookmark = db.Bookmarks
                .Include("User")
                .Include("Category")
                .Where(x => x.Id == id).FirstOrDefault();
            if (bookmark == null)
            {
                return HttpNotFound();
            }

            var model = new DisplayBookmarkViewModel(bookmark);

            return View(model);
        }

        //
        // GET: /Bookmarks/Create

        [Authorize, InitializeSimpleMembership]
        public ActionResult Create()
        {
            var user = GetUser();
            var userCategories = db.Categories
                .Where(x => x.User.UserId == user.UserId && !x.IsDeleted)
                .Select(x => x.Name)
                .ToList();

            ViewData["Category"] = new SelectList(userCategories);
            return View();
        }

        //
        // POST: /Bookmarks/Create

        [HttpPost]
        [ValidateAntiForgeryToken, InitializeSimpleMembership]
        public ActionResult Create(ManageBookmarkDataViewModel bookmarkModel)
        {
            if (string.IsNullOrEmpty(bookmarkModel.Title))
            {
                bookmarkModel.Title = bookmarkModel.Url;
            }
            var user = GetUser();
            var existing = db.Bookmarks.Where(x => x.Url == bookmarkModel.Url && x.User.UserId == user.UserId).FirstOrDefault();
            if (existing != null)
            {
                if (ModelState.IsValid && existing.User.UserId == user.UserId)
                {
                    existing.IsDeleted = false;
                    existing.LastEdit = DateTime.Now;
                    existing.Title = bookmarkModel.Title;
                    existing.Url = bookmarkModel.Url;
                    existing.Description = bookmarkModel.Description;
                    existing.Category = LoadOrCreateCategory(bookmarkModel.Category);
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    var newBookmark = new Bookmark();
                    newBookmark.IsDeleted = false;
                    newBookmark.LastEdit = DateTime.Now;
                    newBookmark.Title = bookmarkModel.Title;
                    newBookmark.Url = bookmarkModel.Url;
                    newBookmark.Description = bookmarkModel.Description;
                    newBookmark.User = user;
                    newBookmark.Category = LoadOrCreateCategory(bookmarkModel.Category);

                    db.Bookmarks.Add(newBookmark);
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Bookmarks/Edit/5

        [InitializeSimpleMembership]
        public ActionResult Edit(int id = 0)
        {
            Bookmark bookmark = db.Bookmarks.Find(id);
            if (bookmark == null)
            {
                return HttpNotFound();
            }

            ManageBookmarkDataViewModel model = new ManageBookmarkDataViewModel()
            {
                Id = bookmark.Id,
                Description = bookmark.Description,
                Title = bookmark.Title,
                Url = bookmark.Url,
                Category = bookmark.Category.Name
            };

            var user = GetUser();
            var userCategories = db.Categories
                .Where(x => x.User.UserId == user.UserId && !x.IsDeleted)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value =x.Name,
                    Selected = x.Id==bookmark.Category.Id,
                })
                .ToList();

            ViewData["Category"] = userCategories;

            return View(model);
        }

        //
        // POST: /Bookmarks/Edit/5

        [HttpPost]
        [InitializeSimpleMembership]
        [ValidateAntiForgeryToken, Authorize]
        public ActionResult Edit(ManageBookmarkDataViewModel bookmarkModel)
        {
            if (string.IsNullOrEmpty(bookmarkModel.Title))
            {
                bookmarkModel.Title = bookmarkModel.Url;
            }

            var user = GetUser();
            var existing = db.Bookmarks
                .Where(x => x.Id == bookmarkModel.Id && x.User.UserId == user.UserId)
                .FirstOrDefault();

            if (existing != null)
            {
                if (ModelState.IsValid && existing.User.UserId == user.UserId)
                {
                    existing.IsDeleted = false;
                    existing.LastEdit = DateTime.Now;
                    existing.Title = bookmarkModel.Title;
                    existing.Url = bookmarkModel.Url;
                    existing.Description = bookmarkModel.Description;
                    existing.Category = LoadOrCreateCategory(bookmarkModel.Category);
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Bookmarks/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Bookmark bookmark = db.Bookmarks.Find(id);
            if (bookmark == null)
            {
                return HttpNotFound();
            }

            return View(bookmark);
        }

        //
        // POST: /Bookmarks/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken, InitializeSimpleMembership]
        public ActionResult DeleteConfirmed(int id)
        {
            Bookmark bookmark = db.Bookmarks.Find(id);
            var user = GetUser();
            if (bookmark.User.UserId == user.UserId)
            {
                bookmark.IsDeleted = true;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        [InitializeSimpleMembership]
        private UserProfile GetUser()
        {
            UserProfile user = db.UserProfiles.Where(x => x.UserId == WebSecurity.CurrentUserId).FirstOrDefault();
            return user;
        }

        [InitializeSimpleMembership]
        private Category LoadOrCreateCategory(string categoryName)
        {
            var user = GetUser();
            var existing = db.Categories.Where(x => x.Name == categoryName).FirstOrDefault();
            if (existing == null)
            {
                var newCategory = new Category()
                {
                    IsDeleted = false,
                    Name = categoryName,
                    User = user
                };
                db.SaveChanges();

                return newCategory;
            }
            else
            {
                return existing;
            }
        }
    }
}

Bookmarks.Web/Views/Bookmarks/Create.cshtml
@model Bookmarks.Web.ViewModels.ManageBookmarkDataViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="bookmarks-create-edit">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Bookmark</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Category)
            </div>
            <div class="editor-field">
                @Html.DropDownList("Category")
            </div>

            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bookmarks.Web/Views/Bookmarks/Delete.cshtml
@model Bookmarks.Models.Bookmark

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="bookmarks-details-delete">
    <fieldset>
        <legend>Bookmark</legend>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Url)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Url)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Title)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Title)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Description)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Description)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.LastEdit)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.LastEdit)
        </div>
    </fieldset>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Bookmarks.Web/Views/Bookmarks/Details.cshtml
@model Bookmarks.Web.ViewModels.DisplayBookmarkViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="bookmarks-details-delete">
    <fieldset>
        <legend>Bookmark</legend>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Url)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Url)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Title)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Title)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.Description)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Description)
        </div>

        <div class="display-label">
            @Html.DisplayNameFor(model => model.LastEdit)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.LastEdit)
        </div>

    </fieldset>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bookmarks.Web/Views/Bookmarks/Edit.cshtml
@model Bookmarks.Web.ViewModels.ManageBookmarkDataViewModel

@{
    ViewBag.Title = "Edit Bookmark";
}

<h2>Edit Bookmark</h2>
<div class="bookmarks-create-edit">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Bookmark</legend>
            @Html.HiddenFor(model => model.Id)

            <div class="editor-label">
                @Html.LabelFor(model => model.Url)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Title)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Description)
            </div>
            <div class="editor-field">
                @Html.TextAreaFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Category)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.Category, ViewData["Category"] as IEnumerable<SelectListItem>, Model.Category)

            </div>

            <p>
                <input type="submit" value="Apply Changes" />
            </p>
        </fieldset>
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bookmarks.Web/Views/Bookmarks/Index.cshtml
@model IEnumerable<Bookmarks.Web.ViewModels.DisplayBookmarkViewModel>

@{
    ViewBag.Title = "ViewTable";
}

<h2>Bookmarks</h2>

<div class="bookmarks-container">

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    <div class="bookmarks-create-form">
        @using (Html.BeginForm("Index", "Bookmarks", FormMethod.Get))
        {
            <p>

                Category:  @Html.DropDownList("categoryName", ViewData["Category"] as IEnumerable<SelectListItem>, string.Empty)
                Title: @Html.TextBox("title", string.Empty)
                Url: @Html.TextBox("url", string.Empty)
                <br />
                <input type="submit" value="Filter" />
            </p>
        }
    </div>

    <table class="bookmarksTable detailed">
        <tr>
            <th class="cell-detailed-col1"></th>
            <th class="cell-detailed-col2">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th class="cell-detailed-col3">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th class="cell-detailed-col4">
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th class="cell-detailed-col5">Controls
            </th>
        </tr>

        @{int counter = 0;}
        @foreach (var item in Model)
        {
            counter++;
            <tr>
                <td class="cell-detailed-col1">
                    @counter
                </td>
                <td class="cell-detailed-col2">
                    <span class="cell-wrapper"><a href="@item.Url" target="_blank" class="bookmark-link">@item.Title</a></span>
                </td>
                <td class="cell-detailed-col3" style="text-overflow:ellipsis;">
                   <span class="cell-wrapper">@Html.DisplayFor(modelItem => item.Description)</span>
                </td>
                <td class="cell-detailed-col4">
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td class="cell-detailed-col5">
                    <div class="bookmarks-controls">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </div>
                </td>
            </tr>
        }

    </table>
</div>